
listen_address: 0.0.0.0:9991
database:
  url: postgres://admin:password@db1:5432/dpsa
min_job_discovery_delay_secs: 5
max_job_discovery_delay_secs: 10
max_concurrent_job_workers: 2
worker_lease_duration_secs: 10
worker_lease_clock_skew_allowance_secs: 3
maximum_attempts_before_failure: 10

# force_json_output: true
logging_config:
  tokio_console_config:
    enabled: true
    listen_address: 127.0.0.1:6669
