
listen_address: 0.0.0.0:9992
max_upload_batch_size: 50
max_upload_batch_write_delay_ms: 500
database:
  url: postgres://admin:password@db2:5432/dpsa
batch_aggregation_shard_count: 5

# logging_config:
#   tokio_console_config:
#     enabled: true
#     listen_address: 127.0.0.1:6669
