id: 8TvsLu07GzmyBrMvITwPNpDapjPOkE42IPeg7ggIEWM
aggregator_endpoints:
- http://localhost:9991/
- http://localhost:9992/
vdaf: Prio3Aes128Count
role: Leader
vdaf_verify_keys:
- AAAAAAAAAAAAAAAAAAAAAA
max_batch_lifetime: 0
min_batch_size: 0
min_batch_duration: 28800
tolerable_clock_skew: 600
collector_hpke_config:
  id: 148
  kem_id: X25519HkdfSha256
  kdf_id: HkdfSha256
  aead_id: Aes128Gcm
  public_key: HBQtMUTT5r_Pl5oHp2COVXS1SjSyPXuzapspqxizuhM
aggregator_auth_tokens:
- MF93RTh2UVRaUWlNY3VwdlhPU2RqQQ
collector_auth_tokens:
- RHZsSUVsOGM0TVVaczBpWDZoOF9TQQ
hpke_keys:
- config:
    id: 250
    kem_id: X25519HkdfSha256
    kdf_id: HkdfSha256
    aead_id: Aes128Gcm
    public_key: kBne_IHdgLB8DCXhA_bGQL1-wGYc7d1J7qyQWM8Zriw
  private_key: CDjfI1lZGBIBJHlwPKJ9MIQtRz6Jytuwpln16tkOt2A
