
listen_address: 0.0.0.0:9991
database:
  url: postgres://admin:password@db1:5432/dpsa
tasks_update_frequency_secs: 10
aggregation_job_creation_interval_secs: 10
min_aggregation_job_size: 2
max_aggregation_job_size: 100
